run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - typecheck
    - gocritic
    - errcheck
    - unused
    - misspell
    - bodyclose
    - nilerr
    - prealloc
    - gosec
    - gofmt
linters-settings:
  gocritic:
    enabled-checks:
      - dupImport
      - ifElseChain
      - nestingReduce
  misspell:
    locale: US
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
